- name: Install Rust toolchain
  uses: dtolnay/rust-toolchain@stable
- name: Install WiX (Windows MSI)
  if: ${{ runner.os == 'Windows' }}
  shell: pwsh
  run: |
    choco install wixtoolset -y
    $wixBin = "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin"
    if (Test-Path $wixBin) {
      Add-Content -Path $env:GITHUB_PATH -Value $wixBin
    }
